## Carga de la base datos

In [1]:
import pandas as pd
import numpy as np
envaj = pd.read_csv("envaj_modulos.csv", encoding = 'unicode_escape', dtype='unicode', sep=',')
envaj.head()

,edo,muni,loca,dia1,mes1,hr_ini1,min_ini1,hr_ter1,min_ter1,dura1,...,p155,p156,p157,sexo,edad1,escol,est,reg,pondeviv1,pondeviv2
0,1,1,367,25,8,10,50,12,8,78,...,NaN,NaN,NaN,1,12,4,1,4,5048,4331
1,1,1,367,25,8,12,30,13,20,50,...,NaN,NaN,NaN,2,16,5,1,4,5048,4331
2,1,1,367,25,8,17,20,18,30,70,...,NaN,NaN,NaN,2,21,5,1,4,5048,4331
3,1,1,367,25,8,19,3,20,35,92,...,NaN,NaN,NaN,1,12,4,1,4,5048,4331
4,1,1,367,25,8,17,41,18,36,55,...,NaN,NaN,NaN,1,17,6,1,4,5048,4331

## Limpieza datos nulos - vacios

In [2]:
#Mean: 26, 32, 33
for column in envaj:
    if(column == "p26" or column == "p32" or column == "p33"):
        envaj[column] = envaj[column].astype(float)
        envaj[column].fillna(value=envaj[column].mean(), inplace=True)
    else:
        envaj[column].fillna(envaj[column].mode()[0], inplace=True)
        envaj[column] = envaj[column].astype(int)
envaj.head()

,edo,muni,loca,dia1,mes1,hr_ini1,min_ini1,hr_ter1,min_ter1,dura1,...,p155,p156,p157,sexo,edad1,escol,est,reg,pondeviv1,pondeviv2
0,1,1,367,25,8,10,50,12,8,78,...,3,1,1,1,12,4,1,4,5048,4331
1,1,1,367,25,8,12,30,13,20,50,...,3,1,1,2,16,5,1,4,5048,4331
2,1,1,367,25,8,17,20,18,30,70,...,3,1,1,2,21,5,1,4,5048,4331
3,1,1,367,25,8,19,3,20,35,92,...,3,1,1,1,12,4,1,4,5048,4331
4,1,1,367,25,8,17,41,18,36,55,...,3,1,1,1,17,6,1,4,5048,4331

## Reemplazar codigos sin utilidad por moda/media

In [3]:
envaj["p1"] = np.where(envaj["p1"] >= 8, envaj["p1"].mode()[0], envaj["p1"])
envaj["p2"] = np.where(envaj["p2"] >= 8, envaj["p2"].mode()[0], envaj["p2"])
envaj["p3"] = np.where(envaj["p3"] >= 8, envaj["p3"].mode()[0], envaj["p3"])
envaj["p4a"] = np.where(envaj["p4a"] >= 98, envaj["p4a"].mode()[0], envaj["p4a"])

envaj["p5_1"] = np.where(envaj["p5_1"] >= 98, envaj["p5_1"].mode()[0], envaj["p5_1"])
envaj["p5_2"] = np.where(envaj["p5_2"] >= 98, envaj["p5_2"].mode()[0], envaj["p5_2"])
envaj["p5_3"] = np.where(envaj["p5_3"] >= 98, envaj["p5_3"].mode()[0], envaj["p5_3"])
envaj["p5_4"] = np.where(envaj["p5_4"] >= 98, envaj["p5_4"].mode()[0], envaj["p5_4"])
envaj["p5_5"] = np.where(envaj["p5_5"] >= 98, envaj["p5_5"].mode()[0], envaj["p5_5"])
envaj["p5_6"] = np.where(envaj["p5_6"] >= 98, envaj["p5_6"].mode()[0], envaj["p5_6"])
envaj["p5_7"] = np.where(envaj["p5_7"] >= 98, envaj["p5_7"].mode()[0], envaj["p5_7"])
envaj["p5_8"] = np.where(envaj["p5_8"] >= 98, envaj["p5_8"].mode()[0], envaj["p5_8"])
envaj["p5_9"] = np.where(envaj["p5_9"] >= 98, envaj["p5_9"].mode()[0], envaj["p5_9"])

envaj["p6_1"] = np.where(envaj["p6_1"] >= 8, envaj["p6_1"].mode()[0], envaj["p6_1"])
envaj["p6_2"] = np.where(envaj["p6_2"] >= 8, envaj["p6_2"].mode()[0], envaj["p6_2"])
envaj["p6_3"] = np.where(envaj["p6_3"] >= 8, envaj["p6_3"].mode()[0], envaj["p6_3"])
envaj["p6_4"] = np.where(envaj["p6_4"] >= 8, envaj["p6_4"].mode()[0], envaj["p6_4"])
envaj["p6_5"] = np.where(envaj["p6_5"] >= 8, envaj["p6_6"].mode()[0], envaj["p6_5"])
envaj["p6_6"] = np.where(envaj["p6_6"] >= 8, envaj["p6_6"].mode()[0], envaj["p6_6"])
envaj["p6_7"] = np.where(envaj["p6_7"] >= 8, envaj["p6_7"].mode()[0], envaj["p6_7"])

envaj["p7"] = np.where(envaj["p7"] >= 11, envaj["p7"].mode()[0], envaj["p7"])
envaj["p8"] = np.where(envaj["p8"] >= 4, envaj["p8"].mode()[0], envaj["p8"])
envaj["p9_1"] = np.where(envaj["p9_1"] >= 15, envaj["p9_1"].mode()[0], envaj["p9_1"])
envaj["p10"] = np.where(envaj["p10"] >= 8, envaj["p10"].mode()[0], envaj["p10"])
envaj["p11"] = np.where(envaj["p11"] >= 11, envaj["p11"].mode()[0], envaj["p11"])
envaj["p12"] = np.where(envaj["p12"] >= 8, envaj["p12"].mode()[0], envaj["p12"])
envaj["p13"] = np.where(envaj["p13"] >= 8, envaj["p13"].mode()[0], envaj["p13"])

envaj["p14_1"] = np.where(envaj["p14_1"] >= 7, envaj["p14_1"].mode()[0], envaj["p14_1"])
envaj["p14_2"] = np.where(envaj["p14_2"] >= 7, envaj["p14_2"].mode()[0], envaj["p14_2"])
envaj["p14_3"] = np.where(envaj["p14_3"] >= 7, envaj["p14_3"].mode()[0], envaj["p14_3"])
envaj["p14_4"] = np.where(envaj["p14_4"] >= 7, envaj["p14_4"].mode()[0], envaj["p14_4"])
envaj["p14_5"] = np.where(envaj["p14_5"] >= 7, envaj["p14_6"].mode()[0], envaj["p14_5"])
envaj["p14_6"] = np.where(envaj["p14_6"] >= 7, envaj["p14_6"].mode()[0], envaj["p14_6"])
envaj["p14_7"] = np.where(envaj["p14_7"] >= 7, envaj["p14_7"].mode()[0], envaj["p14_7"])
envaj["p14_8"] = np.where(envaj["p14_8"] >= 7, envaj["p14_8"].mode()[0], envaj["p14_8"])
envaj["p14_9"] = np.where(envaj["p14_9"] >= 7, envaj["p14_9"].mode()[0], envaj["p14_9"])
envaj["p14_10"] = np.where(envaj["p14_10"] >= 7, envaj["p14_10"].mode()[0], envaj["p14_10"])

envaj["p15"] = np.where(envaj["p15"] >= 5, envaj["p15"].mode()[0], envaj["p15"])
envaj["p16"] = np.where(envaj["p16"] >= 3, envaj["p16"].mode()[0], envaj["p16"])
envaj["p17"] = np.where(envaj["p17"] >= 3, envaj["p17"].mode()[0], envaj["p17"])
envaj["p18"] = np.where(envaj["p18"] >= 7, envaj["p18"].mode()[0], envaj["p18"])
envaj["p19_1"] = np.where(envaj["p19_1"] >= 12, envaj["p19_1"].mode()[0], envaj["p19_1"])
envaj["p20"] = np.where(envaj["p20"] >= 8, envaj["p20"].mode()[0], envaj["p20"])
envaj["p21"] = np.where(envaj["p21"] >= 8, envaj["p21"].mode()[0], envaj["p21"])

envaj["p22_1"] = np.where(envaj["p22_1"] >= 8, envaj["p22_1"].mode()[0], envaj["p22_1"])
envaj["p22_2"] = np.where(envaj["p22_2"] >= 8, envaj["p22_2"].mode()[0], envaj["p22_2"])
envaj["p22_3"] = np.where(envaj["p22_3"] >= 8, envaj["p22_3"].mode()[0], envaj["p22_3"])
envaj["p22_4"] = np.where(envaj["p22_4"] >= 8, envaj["p22_4"].mode()[0], envaj["p22_4"])

envaj["p23"] = np.where(envaj["p23"] >= 8, envaj["p23"].mode()[0], envaj["p23"])
envaj["p25"] = np.where(envaj["p25"] >= 8, envaj["p25"].mode()[0], envaj["p25"])
envaj["p26"] = np.where(envaj["p26"] >= 98, envaj["p26"].mean(), envaj["p26"])
envaj["p27"] = np.where(envaj["p27"] >= 3, envaj["p27"].mode()[0], envaj["p27"])

envaj["p28_1"] = np.where(envaj["p28_1"] >= 8, envaj["p28_1"].mode()[0], envaj["p28_1"])
envaj["p28_2"] = np.where(envaj["p28_2"] >= 8, envaj["p28_2"].mode()[0], envaj["p28_2"])

envaj["p29"] = np.where(envaj["p29"] >= 8, envaj["p29"].mode()[0], envaj["p29"])
envaj["p30_1"] = np.where(envaj["p30_1"] >= 7, envaj["p30_1"].mode()[0], envaj["p30_1"])
envaj["p31"] = np.where(envaj["p31"] >= 8, envaj["p31"].mode()[0], envaj["p31"])
envaj["p32"] = np.where(envaj["p32"] >= 98, envaj["p32"].mean(), envaj["p32"])
envaj["p33"] = np.where(envaj["p33"] >= 98, envaj["p33"].mean(), envaj["p33"])
envaj["p34"] = np.where(envaj["p34"] >= 98, envaj["p34"].mode()[0], envaj["p34"])

envaj["p35_1"] = np.where(envaj["p35_1"] >= 98, envaj["p35_1"].mode()[0], envaj["p35_1"])
envaj["p35_2"] = np.where(envaj["p35_2"] >= 98, envaj["p35_2"].mode()[0], envaj["p35_2"])
envaj["p35_3"] = np.where(envaj["p35_3"] >= 98, envaj["p35_3"].mode()[0], envaj["p35_3"])
envaj["p35_4"] = np.where(envaj["p35_4"] >= 98, envaj["p35_4"].mode()[0], envaj["p35_4"])
envaj["p35_5"] = np.where(envaj["p35_5"] >= 98, envaj["p35_6"].mode()[0], envaj["p35_5"])
envaj["p35_6"] = np.where(envaj["p35_6"] >= 98, envaj["p35_6"].mode()[0], envaj["p35_6"])
envaj["p35_7"] = np.where(envaj["p35_7"] >= 98, envaj["p35_7"].mode()[0], envaj["p35_7"])
envaj["p35_8"] = np.where(envaj["p35_8"] >= 98, envaj["p35_8"].mode()[0], envaj["p35_8"])
envaj["p35_9"] = np.where(envaj["p35_9"] >= 98, envaj["p35_9"].mode()[0], envaj["p35_9"])
envaj["p35_10"] = np.where(envaj["p35_10"] >= 98, envaj["p35_10"].mode()[0], envaj["p35_10"])
envaj["p35_11"] = np.where(envaj["p35_11"] >= 98, envaj["p35_11"].mode()[0], envaj["p35_11"])
envaj["p35_12"] = np.where(envaj["p35_12"] >= 98, envaj["p35_12"].mode()[0], envaj["p35_12"])
envaj["p35_13"] = np.where(envaj["p35_13"] >= 98, envaj["p35_13"].mode()[0], envaj["p35_13"])
envaj["p35_14"] = np.where(envaj["p35_14"] >= 98, envaj["p35_14"].mode()[0], envaj["p35_14"])

envaj["p36_1"] = np.where(envaj["p36_1"] >= 4, envaj["p36_1"].mode()[0], envaj["p36_1"])
envaj["p36_2"] = np.where(envaj["p36_2"] >= 4, envaj["p36_2"].mode()[0], envaj["p36_2"])
envaj["p36_3"] = np.where(envaj["p36_3"] >= 4, envaj["p36_3"].mode()[0], envaj["p36_3"])
envaj["p36_4"] = np.where(envaj["p36_4"] >= 4, envaj["p36_4"].mode()[0], envaj["p36_4"])
envaj["p36_5"] = np.where(envaj["p36_5"] >= 4, envaj["p36_6"].mode()[0], envaj["p36_5"])
envaj["p36_6"] = np.where(envaj["p36_6"] >= 4, envaj["p36_6"].mode()[0], envaj["p36_6"])
envaj["p36_7"] = np.where(envaj["p36_7"] >= 4, envaj["p36_7"].mode()[0], envaj["p36_7"])

envaj["p37_1"] = np.where(envaj["p37_1"] >= 8, envaj["p37_1"].mode()[0], envaj["p37_1"])
envaj["p37_2"] = np.where(envaj["p37_2"] >= 8, envaj["p37_2"].mode()[0], envaj["p37_2"])
envaj["p37_3"] = np.where(envaj["p37_3"] >= 8, envaj["p37_3"].mode()[0], envaj["p37_3"])
envaj["p37_4"] = np.where(envaj["p37_4"] >= 8, envaj["p37_4"].mode()[0], envaj["p37_4"])
envaj["p37_5"] = np.where(envaj["p37_5"] >= 8, envaj["p37_6"].mode()[0], envaj["p37_5"])
envaj["p37_6"] = np.where(envaj["p37_6"] >= 8, envaj["p37_6"].mode()[0], envaj["p37_6"])
envaj["p37_7"] = np.where(envaj["p37_7"] >= 8, envaj["p37_7"].mode()[0], envaj["p37_7"])

envaj["p38"] = np.where(envaj["p38"] >= 8, envaj["p38"].mode()[0], envaj["p38"])
envaj["p39"] = np.where(envaj["p39"] >= 8, envaj["p39"].mode()[0], envaj["p39"])
envaj["p40"] = np.where(envaj["p40"] >= 8, envaj["p40"].mode()[0], envaj["p40"])

envaj["p41_1"] = np.where(envaj["p41_1"] >= 8, envaj["p41_1"].mode()[0], envaj["p41_1"])
envaj["p41_2"] = np.where(envaj["p41_2"] >= 8, envaj["p41_2"].mode()[0], envaj["p41_2"])
envaj["p41_3"] = np.where(envaj["p41_3"] >= 8, envaj["p41_3"].mode()[0], envaj["p41_3"])
envaj["p41_4"] = np.where(envaj["p41_4"] >= 8, envaj["p41_4"].mode()[0], envaj["p41_4"])
envaj["p41_5"] = np.where(envaj["p41_5"] >= 8, envaj["p41_6"].mode()[0], envaj["p41_5"])
envaj["p41_6"] = np.where(envaj["p41_6"] >= 8, envaj["p41_6"].mode()[0], envaj["p41_6"])
envaj["p41_7"] = np.where(envaj["p41_7"] >= 8, envaj["p41_7"].mode()[0], envaj["p41_7"])
envaj["p41_8"] = np.where(envaj["p41_8"] >= 8, envaj["p41_8"].mode()[0], envaj["p41_8"])
envaj["p41_9"] = np.where(envaj["p41_9"] >= 8, envaj["p41_9"].mode()[0], envaj["p41_9"])
envaj["p41_10"] = np.where(envaj["p41_10"] >= 8, envaj["p41_10"].mode()[0], envaj["p41_10"])
envaj["p41_11"] = np.where(envaj["p41_11"] >= 8, envaj["p41_11"].mode()[0], envaj["p41_11"])

envaj["p42"] = np.where(envaj["p42"] >= 8, envaj["p42"].mode()[0], envaj["p42"])
envaj["p43"] = np.where(envaj["p43"] >= 8, envaj["p43"].mode()[0], envaj["p43"])
envaj["p44"] = np.where(envaj["p44"] >= 8, envaj["p44"].mode()[0], envaj["p44"])

envaj["p45_1"] = np.where(envaj["p45_1"] >= 8, envaj["p45_1"].mode()[0], envaj["p45_1"])
envaj["p45_2"] = np.where(envaj["p45_2"] >= 8, envaj["p45_2"].mode()[0], envaj["p45_2"])
envaj["p45_3"] = np.where(envaj["p45_3"] >= 8, envaj["p45_3"].mode()[0], envaj["p45_3"])
envaj["p45_4"] = np.where(envaj["p45_4"] >= 8, envaj["p45_4"].mode()[0], envaj["p45_4"])
envaj["p45_5"] = np.where(envaj["p45_5"] >= 8, envaj["p45_6"].mode()[0], envaj["p45_5"])
envaj["p45_6"] = np.where(envaj["p45_6"] >= 8, envaj["p45_6"].mode()[0], envaj["p45_6"])
envaj["p45_7"] = np.where(envaj["p45_7"] >= 8, envaj["p45_7"].mode()[0], envaj["p45_7"])
envaj["p45_8"] = np.where(envaj["p45_8"] >= 8, envaj["p45_8"].mode()[0], envaj["p45_8"])
envaj["p45_9"] = np.where(envaj["p45_9"] >= 8, envaj["p45_9"].mode()[0], envaj["p45_9"])
envaj["p45_10"] = np.where(envaj["p45_10"] >= 8, envaj["p45_10"].mode()[0], envaj["p45_10"])

envaj["p46_1"] = np.where(envaj["p46_1"] >= 5, envaj["p46_1"].mode()[0], envaj["p46_1"])
envaj["p46_2"] = np.where(envaj["p46_2"] >= 5, envaj["p46_2"].mode()[0], envaj["p46_2"])
envaj["p46_3"] = np.where(envaj["p46_3"] >= 5, envaj["p46_3"].mode()[0], envaj["p46_3"])
envaj["p46_4"] = np.where(envaj["p46_4"] >= 5, envaj["p46_4"].mode()[0], envaj["p46_4"])
envaj["p46_5"] = np.where(envaj["p46_5"] >= 5, envaj["p46_6"].mode()[0], envaj["p46_5"])
envaj["p46_6"] = np.where(envaj["p46_6"] >= 5, envaj["p46_6"].mode()[0], envaj["p46_6"])
envaj["p46_7"] = np.where(envaj["p46_7"] >= 5, envaj["p46_7"].mode()[0], envaj["p46_7"])
envaj["p46_8"] = np.where(envaj["p46_8"] >= 5, envaj["p46_8"].mode()[0], envaj["p46_8"])
envaj["p46_9"] = np.where(envaj["p46_9"] >= 5, envaj["p46_9"].mode()[0], envaj["p46_9"])
envaj["p46_10"] = np.where(envaj["p46_10"] >= 5, envaj["p46_10"].mode()[0], envaj["p46_10"])
envaj["p46_11"] = np.where(envaj["p46_11"] >= 5, envaj["p46_11"].mode()[0], envaj["p46_11"])
envaj["p46_12"] = np.where(envaj["p46_12"] >= 5, envaj["p46_12"].mode()[0], envaj["p46_12"])
envaj["p46_13"] = np.where(envaj["p46_13"] >= 5, envaj["p46_13"].mode()[0], envaj["p46_13"])
envaj["p46_14"] = np.where(envaj["p46_14"] >= 5, envaj["p46_14"].mode()[0], envaj["p46_14"])

envaj["p47"] = np.where(envaj["p47"] >= 6, envaj["p47"].mode()[0], envaj["p47"])

envaj["p48_1"] = np.where(envaj["p48_1"] >= 8, envaj["p48_1"].mode()[0], envaj["p48_1"])
envaj["p48_2"] = np.where(envaj["p48_2"] >= 8, envaj["p48_2"].mode()[0], envaj["p48_2"])
envaj["p48_3"] = np.where(envaj["p48_3"] >= 8, envaj["p48_3"].mode()[0], envaj["p48_3"])
envaj["p48_4"] = np.where(envaj["p48_4"] >= 8, envaj["p48_4"].mode()[0], envaj["p48_4"])
envaj["p48_5"] = np.where(envaj["p48_5"] >= 8, envaj["p48_6"].mode()[0], envaj["p48_5"])
envaj["p48_6"] = np.where(envaj["p48_6"] >= 8, envaj["p48_6"].mode()[0], envaj["p48_6"])
envaj["p48_7"] = np.where(envaj["p48_7"] >= 8, envaj["p48_7"].mode()[0], envaj["p48_7"])
envaj["p48_8"] = np.where(envaj["p48_8"] >= 8, envaj["p48_8"].mode()[0], envaj["p48_8"])
envaj["p48_9"] = np.where(envaj["p48_9"] >= 8, envaj["p48_9"].mode()[0], envaj["p48_9"])
envaj["p48_10"] = np.where(envaj["p48_10"] >= 8, envaj["p48_10"].mode()[0], envaj["p48_10"])
envaj["p48_11"] = np.where(envaj["p48_11"] >= 8, envaj["p48_11"].mode()[0], envaj["p48_11"])
envaj["p48_12"] = np.where(envaj["p48_12"] >= 8, envaj["p48_12"].mode()[0], envaj["p48_12"])
envaj["p48_13"] = np.where(envaj["p48_13"] >= 8, envaj["p48_13"].mode()[0], envaj["p48_13"])

envaj["p134"] = np.where(envaj["p134"] >= 8, envaj["p134"].mode()[0], envaj["p134"])
envaj["p135"] = np.where(envaj["p135"] >= 8, envaj["p135"].mode()[0], envaj["p135"])
envaj["p136_1"] = np.where(envaj["p136_1"] >= 8, envaj["p136_1"].mode()[0], envaj["p136_1"])
envaj["p136_2"] = np.where(envaj["p136_2"] >= 8, envaj["p136_2"].mode()[0], envaj["p136_2"])
envaj["p137"] = np.where(envaj["p137"] >= 6, envaj["p137"].mode()[0], envaj["p137"])
envaj["p138"] = np.where(envaj["p138"] >= 97, envaj["p138"].mode()[0], envaj["p138"])
envaj["p139"] = np.where(envaj["p139"] >= 9, envaj["p139"].mode()[0], envaj["p139"])
envaj["p140_1"] = np.where(envaj["p140_1"] >= 11, envaj["p140_1"].mode()[0], envaj["p140_1"])

envaj["p141_1"] = np.where(envaj["p141_1"] >= 8, envaj["p141_1"].mode()[0], envaj["p141_1"])
envaj["p141_2"] = np.where(envaj["p141_2"] >= 8, envaj["p141_2"].mode()[0], envaj["p141_2"])
envaj["p141_3"] = np.where(envaj["p141_3"] >= 8, envaj["p141_3"].mode()[0], envaj["p141_3"])
envaj["p141_4"] = np.where(envaj["p141_4"] >= 8, envaj["p141_4"].mode()[0], envaj["p141_4"])
envaj["p141_5"] = np.where(envaj["p141_5"] >= 8, envaj["p141_6"].mode()[0], envaj["p141_5"])
envaj["p141_6"] = np.where(envaj["p141_6"] >= 8, envaj["p141_6"].mode()[0], envaj["p141_6"])
envaj["p141_7"] = np.where(envaj["p141_7"] >= 8, envaj["p141_7"].mode()[0], envaj["p141_7"])
envaj["p141_8"] = np.where(envaj["p141_8"] >= 8, envaj["p141_8"].mode()[0], envaj["p141_8"])
envaj["p141_9"] = np.where(envaj["p141_9"] >= 8, envaj["p141_9"].mode()[0], envaj["p141_9"])
envaj["p141_10"] = np.where(envaj["p141_10"] >= 8, envaj["p141_10"].mode()[0], envaj["p141_10"])

envaj["p142"] = np.where(envaj["p142"] >= 98, envaj["p142"].mode()[0], envaj["p142"])
envaj["p143"] = np.where(envaj["p143"] >= 8, envaj["p143"].mode()[0], envaj["p143"])
envaj["p144"] = np.where(envaj["p144"] >= 6, envaj["p144"].mode()[0], envaj["p144"])

envaj["p145_1"] = np.where(envaj["p145_1"] >= 8, envaj["p145_1"].mode()[0], envaj["p145_1"])
envaj["p145_2"] = np.where(envaj["p145_2"] >= 8, envaj["p145_2"].mode()[0], envaj["p145_2"])
envaj["p145_3"] = np.where(envaj["p145_3"] >= 8, envaj["p145_3"].mode()[0], envaj["p145_3"])
envaj["p145_4"] = np.where(envaj["p145_4"] >= 8, envaj["p145_4"].mode()[0], envaj["p145_4"])
envaj["p145_5"] = np.where(envaj["p145_5"] >= 8, envaj["p145_6"].mode()[0], envaj["p145_5"])
envaj["p145_6"] = np.where(envaj["p145_6"] >= 8, envaj["p145_6"].mode()[0], envaj["p145_6"])
envaj["p145_7"] = np.where(envaj["p145_7"] >= 8, envaj["p145_7"].mode()[0], envaj["p145_7"])
envaj["p145_8"] = np.where(envaj["p145_8"] >= 8, envaj["p145_8"].mode()[0], envaj["p145_8"])
envaj["p145_9"] = np.where(envaj["p145_9"] >= 8, envaj["p145_9"].mode()[0], envaj["p145_9"])
envaj["p145_10"] = np.where(envaj["p145_10"] >= 8, envaj["p145_10"].mode()[0], envaj["p145_10"])
envaj["p145_11"] = np.where(envaj["p145_11"] >= 8, envaj["p145_11"].mode()[0], envaj["p145_11"])
envaj["p145_12"] = np.where(envaj["p145_12"] >= 8, envaj["p145_12"].mode()[0], envaj["p145_12"])
envaj["p145_13"] = np.where(envaj["p145_13"] >= 8, envaj["p145_13"].mode()[0], envaj["p145_13"])

envaj["p146"] = np.where(envaj["p146"] >= 8, envaj["p146"].mode()[0], envaj["p146"])
envaj["p147"] = np.where(envaj["p147"] >= 8, envaj["p147"].mode()[0], envaj["p147"])
envaj["p148"] = np.where(envaj["p148"] >= 4, envaj["p148"].mode()[0], envaj["p148"])
envaj["p149"] = np.where(envaj["p149"] >= 3, envaj["p149"].mode()[0], envaj["p149"])
envaj["p150"] = np.where(envaj["p150"] >= 3, envaj["p150"].mode()[0], envaj["p150"])
envaj["p151"] = np.where(envaj["p151"] >= 8, envaj["p151"].mode()[0], envaj["p151"])
envaj["p152"] = np.where(envaj["p152"] >= 3, envaj["p152"].mode()[0], envaj["p152"])
envaj["p153"] = np.where(envaj["p153"] >= 6, envaj["p153"].mode()[0], envaj["p153"])
envaj["p154"] = np.where(envaj["p154"] >= 4, envaj["p154"].mode()[0], envaj["p154"])
envaj["p155"] = np.where(envaj["p155"] >= 4, envaj["p155"].mode()[0], envaj["p155"])
envaj["p156"] = np.where(envaj["p156"] >= 4, envaj["p156"].mode()[0], envaj["p156"])
envaj["p157"] = np.where(envaj["p157"] >= 6, envaj["p157"].mode()[0], envaj["p157"])

envaj.head()

,edo,muni,loca,dia1,mes1,hr_ini1,min_ini1,hr_ter1,min_ter1,dura1,...,p155,p156,p157,sexo,edad1,escol,est,reg,pondeviv1,pondeviv2
0,1,1,367,25,8,10,50,12,8,78,...,3,1,1,1,12,4,1,4,5048,4331
1,1,1,367,25,8,12,30,13,20,50,...,3,1,1,2,16,5,1,4,5048,4331
2,1,1,367,25,8,17,20,18,30,70,...,3,1,1,2,21,5,1,4,5048,4331
3,1,1,367,25,8,19,3,20,35,92,...,3,1,1,1,12,4,1,4,5048,4331
4,1,1,367,25,8,17,41,18,36,55,...,3,1,1,1,17,6,1,4,5048,4331